name       : lutris
version    : 0.4.16
release    : 17
source     :
    - https://github.com/lutris/lutris/archive/v0.4.16.tar.gz : 0d07e425c3aeff2f50e1327b2c76bae8ae461af8d002b90bdbf111ec56e9a6fb
license    : GPL-3.0-or-later
component  : games
summary    : Install and play any video game easily
description: |
    Lutris is a gaming platform for GNU/Linux. Its goal is to make gaming on Linux as easy as possible by taking care of installing and setting up the game for the user. The only thing you have to do is play the game. It aims to support every game that is playable on Linux.
builddeps  :
    - pkgconfig(python3)
    - python-inotify
    - python3-dbus
    - python3-gobject-devel
    - pyxdg
    - pyyaml
    - xrandr
rundeps    :
    - python-evdev
    - python3-dbus
    - python3-gobject
    - python-inotify
    - pyyaml
    - pyxdg
    - xrandr
build      : |
    %python3_setup
install    : |
    %python3_install
