name       : lutris
version    : 0.4.12
release    : 12
source     :
    - https://github.com/lutris/lutris/archive/v0.4.12.tar.gz : 7fb220a7a47ea7c9095eb665ae4702d78a319dd471a57fbcb1cae0d1f4e8c149
license    : GPL-3.0
component  : games
summary    : Install and play any video game easily
description: |
    Lutris is a gaming platform for GNU/Linux. Its goal is to make gaming on Linux as easy as possible by taking care of installing and setting up the game for the user. The only thing you have to do is play the game. It aims to support every game that is playable on Linux.
builddeps  :
    - pkgconfig(python-3.5)
    - python3-dbus
    - python3-gobject-devel
    - python-inotify
    - pyxdg
    - pyyaml
    - xrandr
rundeps    :
    - python3-dbus
    - python3-gobject
    - python-inotify
    - pyyaml
    - pyxdg
    - xrandr
build      : |
    %python3_setup
install    : |
    %python3_install
