name       : lutris
version    : 0.4.6
release    : 6
source     :
    - https://lutris.net/releases/lutris_0.4.6.tar.xz : fb02a4c2d482f44760681b92b6458b1d85d1eaeb903806a5317fe6e13ae15334
license    : GPL-3.0
component  : games
summary    : Install and play any video game easily
description: |
    Lutris is a gaming platform for GNU/Linux. Its goal is to make gaming on Linux as easy as possible by taking care of installing and setting up the game for the user. The only thing you have to do is play the game. It aims to support every game that is playable on Linux.
builddeps  :
    - pkgconfig(python-3.5)
    - python3-dbus
    - python3-gobject-devel
    - python-inotify
    - pyxdg
    - pyyaml
    - xrandr
rundeps    :
    - python3-dbus
    - python3-gobject
    - python-inotify
    - pyyaml
    - pyxdg
    - xrandr
build      : |
    %python3_setup
install    : |
    %python3_install
