name       : lutris
version    : 0.5.8.3
release    : 58
source     :
    - https://github.com/lutris/lutris/archive/v0.5.8.3.tar.gz : 2459db033c8648598c1a19718807b4978a165ff11b40050162ed005b44a52cd3
license    : GPL-3.0-or-later
component  : games
summary    : Install and play any video game easily
description: |
    Lutris is a gaming platform for GNU/Linux. Its goal is to make gaming on Linux as easy as possible by taking care of installing and setting up the game for the user. The only thing you have to do is play the game. It aims to support every game that is playable on Linux.
rundeps    :
    - cabextract
    - gamemode-32bit
    - libgnome-desktop
    - libgnome-keyring
    - libwebkit-gtk
    - mangohud
    - notify-python
    - python-evdev
    - python-gobject
    - python-lxml
    - python-magic
    - python-pillow
    - python-requests
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-Reorder-iter_lib_folders-for-gentoo.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
