name       : lutris
version    : 0.4.23
release    : 26
source     :
    - https://github.com/lutris/lutris/archive/v0.4.23.tar.gz : ca45398e8e7e883b424a32219d54ada0ba23d6629b6fe5e1b5a358fe99799e87
license    : GPL-3.0-or-later
component  : games
summary    : Install and play any video game easily
description: |
    Lutris is a gaming platform for GNU/Linux. Its goal is to make gaming on Linux as easy as possible by taking care of installing and setting up the game for the user. The only thing you have to do is play the game. It aims to support every game that is playable on Linux.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python3)
    - python-evdev
    - python-inotify
    - python3-dbus
    - python3-gobject-devel
    - pyxdg
    - pyyaml
rundeps    :
    - gsm
    - keyutils
    - python-evdev
    - python3-dbus
    - python3-gobject
    - python-inotify
    - pyyaml
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
