name       : lutris
version    : 0.4.13
release    : 14
source     :
    - https://github.com/lutris/lutris/archive/v0.4.13.tar.gz : 720ee375104af791f42298ea8d3beb5353ecbb8e933706768d95065724f17114
license    : GPL-3.0
component  : games
summary    : Install and play any video game easily
description: |
    Lutris is a gaming platform for GNU/Linux. Its goal is to make gaming on Linux as easy as possible by taking care of installing and setting up the game for the user. The only thing you have to do is play the game. It aims to support every game that is playable on Linux.
builddeps  :
    - pkgconfig(python-3.5)
    - python3-dbus
    - python3-gobject-devel
    - python-inotify
    - pyxdg
    - pyyaml
    - xrandr
rundeps    :
    - python3-dbus
    - python3-gobject
    - python-inotify
    - pyyaml
    - pyxdg
    - xrandr
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-register-URL.-404s-without-a-slash.patch
build      : |
    %python3_setup
install    : |
    %python3_install
