name       : lutris
version    : 0.5.1.1
release    : 34
source     :
    - https://github.com/lutris/lutris/archive/v0.5.1.1.tar.gz : fb9dbbe86e3578bac6c36c35590ee50c231e00618f56a5ae8ce6e1b8cc3c5806
license    : GPL-3.0-or-later
component  : games
summary    : Install and play any video game easily
description: |
    Lutris is a gaming platform for GNU/Linux. Its goal is to make gaming on Linux as easy as possible by taking care of installing and setting up the game for the user. The only thing you have to do is play the game. It aims to support every game that is playable on Linux.
rundeps    :
    - libgnome-desktop
    - libgnome-keyring
    - libwebkit-gtk
    - notify-python
    - python-evdev
    - python-pillow
    - python-requests
    - python3-gobject
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-prompt-for-donation-that-also-opens-up-the-do.patch
build      : |
    %python3_setup
install    : |
    %python3_install
