name       : lutris
version    : 0.4.14
release    : 16
source     :
    - https://github.com/lutris/lutris/archive/v0.4.14.tar.gz : abd3654d71151e6c1c2a882e5b4ad6199bcb2102f39d6411bafc69b0efbe44f5
license    : GPL-3.0
component  : games
summary    : Install and play any video game easily
description: |
    Lutris is a gaming platform for GNU/Linux. Its goal is to make gaming on Linux as easy as possible by taking care of installing and setting up the game for the user. The only thing you have to do is play the game. It aims to support every game that is playable on Linux.
builddeps  :
    - pkgconfig(python3)
    - python3-dbus
    - python3-gobject-devel
    - python-inotify
    - pyxdg
    - pyyaml
    - xrandr
rundeps    :
    - python3-dbus
    - python3-gobject
    - python-inotify
    - pyyaml
    - pyxdg
    - xrandr
build      : |
    python3 setup.py build
install    : |
    python3 setup.py install --root="%installroot%"
